### ISSUE TITLE
"Join Slack" 404 error

### ISSUE THREAD

**Issue by kelshew** [codefordc/codefordc-website#2]
The link we put on hackpads for people to join our slack channel doesn’t work. The link on our homepage does work so maybe we should just update what we put on hackpads? Either way, maybe the page that doesn't work needs to be deleted?

This is the url that doesn't work: codefordc.org/joinslack
The one that does work is: https://codefordc.org/resources/slack.html

**Comment by gregjd** [comment]
It looks like while codefordc.org/joinslack doesn't work, codefordc.org/joinslack.html does. (Though oddly, it still takes you to a different page than https://codefordc.org/resources/slack.html.)

Tonight, I can make it so that codefordc.org/joinslack either works directly or redirects.

**Comment by gregjd** [comment]
I think I fixed this the last time I updated the page. Let me know if any problems persist.
