### ISSUE TITLE
Data Portal on home page has incorrect link

### ISSUE THREAD

**Issue by mkalish** [codefordc/codefordc-website#3]
Expected: The link to the data portal found:
<img width="1177" alt="screen shot 2018-07-30 at 1 45 57 pm" src="https://user-images.githubusercontent.com/1225895/43413731-dc7b78c6-93fe-11e8-90b4-311c982b4b8c.png">
should direct to data.codefordc.org 

What actually happens:
User is directed www.data.codefordc.org

**Comment by discdiver** [comment]
Link to http://www.data.codefordc.org/ on home page is now returning an error for me.

> This site can’t be reached www.data.codefordc.org’s server IP address could not be found.
> Search Google for data codeforce org
> ERR_NAME_NOT_RESOLVED
![screen shot 2018-12-07 at 8 47 20 am](https://user-images.githubusercontent.com/7703961/49651659-d1ff1f00-f9fd-11e8-9137-35c5bcacf347.png)

**Comment by gregjd** [comment]
Should be fixed via this commit: https://github.com/codefordc/codefordc.github.com/commit/78aa975da666c85231af3fdc358cc5d9d8768c8e

(May take a few minutes to go up on the live site)
